name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_interpol-rs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update local toolchain
      run: |
        rustup update
        rustup install nightly
        rustup override set nightly
        rustup component add clippy --toolchain nightly-x86_64-unknown-linux-gnu
        rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu

    - name: Toolchain info
      run: |
        cargo --version --verbose
        rustc --version
        cargo clippy --version

    - name: Lint
      run: |
        cd interpol-rs
        cargo fmt -- --check
        cargo clippy -- -D warnings

    - name: Test
      run: |
        cd interpol-rs
        cargo check
        cargo test --all

    - name: Build
      run: |
        cd interpol-rs
        cargo build --release
